---

- name: Install MySQL Python module package
  apt:
    name: python-mysqldb
    state: latest
    update_cache: yes

- name: Remove all anonymous MySQL user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Remove MySQL test database
  mysql_db:
    name: test
    state: absent

- name: Create MySQL database for Zabbix
  mysql_db:
    name: zabbix
    collation: utf8_bin
    encoding: utf8
    state: present
  register: createdb

- name: Import Zabbix database schema
  mysql_db:
    name: zabbix
    collation: utf8_bin
    encoding: utf8
    target: '/usr/share/doc/zabbix-server-mysql/create.sql.gz'
    state: import
  when: createdb|changed

- name: Generate passwords
  set_fact:
    zabbix_web_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=12') }}"
    zabbix_mysql_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}"
    root_mysql_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}"

- name: Template MySQL query to update Zabbix web administrator password
  template:
    src: 'zabbix_admin.sql.j2'
    dest: '/usr/share/doc/zabbix-server-mysql/zabbix_admin.sql'
    owner: root
    group: root
    mode: 0400
  when: createdb|changed

- name: Set Zabbix web administrator password using generated MySQL script
  mysql_db:
    name: zabbix
    target: '/usr/share/doc/zabbix-server-mysql/zabbix_admin.sql'
    state: import
  when: createdb|changed
  register: setzabbixweb

- name: Store Zabbix web administrator password to a file for use later
  copy:
    content: "{{ zabbix_web_password }}"
    dest: '/root/zabbix_admin_password'
    mode: 0600
    owner: root
    group: root
  when: setzabbixweb|changed

- name: Create MySQL user account for Zabbix
  mysql_user:
    name: zabbix
    password: "{{ zabbix_mysql_password }}"
    priv: 'zabbix.*:ALL'
    state: present

- name: Set MySQL root password
  mysql_user:
    check_implicit_admin: yes
    name: root
    host_all: yes
    password: "{{ root_mysql_password }}"

- name: Template my.cnf configuration file
  template:
    src: 'my.cnf.j2'
    dest: '/root/.my.cnf'
    owner: root
    group: root
    mode: 0400

- name: Configure Zabbix server daemon to use MySQL credentials
  replace:
    path: '/etc/zabbix/zabbix_server.conf'
    regexp: '^# DBPassword='
    replace: "DBPassword={{ zabbix_mysql_password }}"
  notify:
    - restart zabbix-server

- name: Configure Zabbix web interface to use MySQL credentials
  template:
    src: 'web_zabbix.conf.php.j2'
    dest: '/etc/zabbix/web/zabbix.conf.php'
    owner: www-data
    group: www-data
    mode: 0644
