---

- name: Install Zabbix package repository
  apt:
    deb: 'https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb'

- name: Install Zabbix packages
  apt:
    name: "{{ zabbix_packages }}"
    state: latest
    update_cache: yes
  vars:
    zabbix_packages:
    - 'zabbix-agent'
    - 'zabbix-server-mysql'
    - 'zabbix-frontend-php'

- name: Check for my.cnf configuration file
  stat:
    path: '/root/.my.cnf'
  register: mycnf

- name: Run MySQL role if it has not already been done
  include_role:
    name: mysql
  when: not mycnf.stat.exists

- name: Ensure that Zabbix server and agent start at boot
  systemd:
    name: "{{ zabbix_services }}"
    enabled: yes
    masked: no
  vars:
    zabbix_services:
    - 'zabbix-agent'
    - 'zabbix-server'
